---

- hosts: all
  tasks:
    - name: Create ec2 instance
      ec2:
        key_name: "{{ keypair_name }}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        group: "{{ security_group_name }}"
        instance_tags:
          instance: "{{ instance_name }}"
          Name: "{{ instance_name }}-{{ lookup('pipe','date +%D_%T_SAST') }}"
          Project: "AWX"
          Created by: "AWX Tower"
          Service: "ansible"
          Team: "PAAS"
        wait: true
        assign_public_ip: false
        exact_count: 1
        region: "{{ region }}"
        count_tag:
          instance: "{{ instance_name }}"
      register: server
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ server.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300


